-- Adiciona colunas technique + rod_type e substitui seed por 53 spots reais PT+ES.

ALTER TABLE fishing_spots
  ADD COLUMN IF NOT EXISTS technique TEXT,
  ADD COLUMN IF NOT EXISTS rod_type  TEXT;

-- Apagar seed anterior (5 spots placeholder)
TRUNCATE fishing_spots;

-- ─────────────────────────────────────────────────────────────────────────────
-- INSERT: 53 spots reais Portugal + Espanha (mar e rio)
-- Coordenadas verificadas: pesca-pt.com · guiadepesca.es · riberafishing.es
-- ─────────────────────────────────────────────────────────────────────────────
INSERT INTO fishing_spots
  (name, lat, lon, country, region, zone_type, tier,
   species, best_season, best_bait, technique, rod_type,
   depth_min, depth_max, bottom_type, car_access, trail_access,
   difficulty, score_avg)
VALUES

-- ── PORTUGAL COSTA ───────────────────────────────────────────────────────────

('Porto da Baleeira — Sagres',
 37.0117, -8.9338, 'PT', 'Algarve', 'costa', 'free',
 ARRAY['Sargo','Safio','Dourada','Robalo'],
 ARRAY['Outono','Inverno','Primavera'],
 ARRAY['Sarda','Amêijoa','Lula'],
 'Fundo / Surfcasting', 'Surf 3.9–4.2m',
 8.0, 25.0, 'Misto (areia e rocha)', true, true, 2, 82),

('Praia do Beliche — Sagres',
 37.0190, -8.9597, 'PT', 'Algarve', 'costa', 'free',
 ARRAY['Carapau','Safio','Sargo'],
 ARRAY['Verão','Outono'],
 ARRAY['Camarão','Amêijoa'],
 'Bóia', 'Rock 3.5m',
 4.0, 15.0, 'Rochoso', true, true, 2, 74),

('Arrifana',
 37.2963, -8.8705, 'PT', 'Algarve', 'costa', 'free',
 ARRAY['Robalo','Sargo','Corvina'],
 ARRAY['Outono','Inverno'],
 ARRAY['Lula','Borracha shad'],
 'Spinning', 'Spinning 9–11ft',
 3.0, 20.0, 'Rochoso', true, false, 3, 83),

('Praia do Amado — Aljezur',
 37.3618, -8.8668, 'PT', 'Algarve', 'costa', 'free',
 ARRAY['Sargo','Pargo','Dourada'],
 ARRAY['Verão','Outono'],
 ARRAY['Camarão','Sarda'],
 'Surfcasting', 'Surf 4.2m',
 2.0, 10.0, 'Areia', true, true, 2, 76),

('Foz do Odeceixe',
 37.4379, -8.7697, 'PT', 'Alentejo Litoral', 'costa', 'free',
 ARRAY['Robalo','Sargo','Dourada'],
 ARRAY['Primavera','Outono'],
 ARRAY['Lula','Minhoca'],
 'Spinning', 'Spinning 9–11ft',
 1.0, 12.0, 'Areia e rocha', true, false, 2, 81),

('Molhe Ria de Alvor',
 37.1297, -8.5870, 'PT', 'Algarve', 'costa', 'free',
 ARRAY['Sargo','Dourada','Robalo'],
 ARRAY['Primavera','Verão','Outono'],
 ARRAY['Camarão','Amêijoa'],
 'Bóia', 'Rock 3.5m',
 1.0, 8.0, 'Fundos mistos', true, true, 1, 79),

('Praia da Rocha — Portimão',
 37.1147, -8.5279, 'PT', 'Algarve', 'costa', 'free',
 ARRAY['Sargo','Dourada','Safio'],
 ARRAY['Outono','Inverno'],
 ARRAY['Minhoca','Amêijoa'],
 'Surfcasting', 'Surf 4.0–4.2m',
 2.0, 8.0, 'Areia', true, true, 1, 75),

('Peniche — Baleal',
 39.3695, -9.3376, 'PT', 'Oeste', 'costa', 'free',
 ARRAY['Robalo','Sargo','Corvina'],
 ARRAY['Outono','Inverno'],
 ARRAY['Lula','Borracha shad'],
 'Spinning', 'Spinning 9–11ft',
 2.0, 15.0, 'Rochoso', true, true, 2, 84),

('Peniche — Molhe Leste',
 37.3575, -9.3803, 'PT', 'Oeste', 'costa', 'free',
 ARRAY['Sargo','Robalo','Dourada'],
 ARRAY['Outono','Inverno'],
 ARRAY['Amêijoa','Sarda'],
 'Bóia', 'Rock 3.5–4m',
 3.0, 12.0, 'Rochoso', true, true, 2, 80),

('Nazaré — Praia Norte',
 39.6083, -9.0718, 'PT', 'Oeste', 'costa', 'free',
 ARRAY['Robalo','Corvina','Linguado'],
 ARRAY['Outono','Inverno'],
 ARRAY['Minhoca','Lula'],
 'Surfcasting', 'Surf 4.2m',
 1.0, 6.0, 'Areia', true, true, 1, 77),

('Figueira da Foz — Molhe Sul',
 40.1453, -8.8625, 'PT', 'Centro', 'costa', 'free',
 ARRAY['Robalo','Linguado','Corvina'],
 ARRAY['Outono','Inverno'],
 ARRAY['Minhoca','Lula'],
 'Surfcasting', 'Surf 4.2m',
 1.0, 5.0, 'Areia', true, true, 1, 76),

('Aveiro — Praia da Barra',
 40.6339, -8.7487, 'PT', 'Centro', 'costa', 'free',
 ARRAY['Robalo','Linguado','Corvina'],
 ARRAY['Outono','Inverno'],
 ARRAY['Minhoca','Amêijoa'],
 'Surfcasting', 'Surf 4.2m',
 1.0, 5.0, 'Areia', true, true, 1, 74),

('Viana do Castelo — Praia Norte',
 41.7009, -8.8467, 'PT', 'Minho', 'costa', 'free',
 ARRAY['Robalo','Linguado'],
 ARRAY['Primavera','Outono'],
 ARRAY['Minhoca','Amêijoa'],
 'Surfcasting', 'Surf 4.0–4.2m',
 1.0, 4.0, 'Areia', true, true, 1, 72),

('Caminha — Praia de Moledo',
 41.8700, -8.8680, 'PT', 'Minho', 'costa', 'free',
 ARRAY['Robalo','Linguado'],
 ARRAY['Primavera','Verão'],
 ARRAY['Minhoca','Camarão'],
 'Surfcasting', 'Surf 4.0m',
 1.0, 4.0, 'Areia', true, true, 1, 70),

('Cascais — Paredão',
 38.6979, -9.4215, 'PT', 'Lisboa', 'costa', 'free',
 ARRAY['Robalo','Sargo'],
 ARRAY['Primavera','Outono'],
 ARRAY['Lula','Borracha shad'],
 'Bóia / Spinning', 'Spinning 9–11ft',
 2.0, 10.0, 'Rochoso', true, true, 1, 76),

('Sesimbra — Costa',
 38.4428, -9.1018, 'PT', 'Setúbal', 'costa', 'free',
 ARRAY['Robalo','Sargo','Dourada'],
 ARRAY['Outono','Inverno'],
 ARRAY['Lula','Borracha shad'],
 'Bóia / Spinning', 'Spinning 9–11ft',
 2.0, 15.0, 'Rochoso', true, true, 2, 84),

('Cabo Espichel',
 38.4141, -9.2164, 'PT', 'Setúbal', 'costa', 'pro',
 ARRAY['Corvina','Robalo','Sargo'],
 ARRAY['Outono','Inverno'],
 ARRAY['Lula','Sarda'],
 'Fundo', 'Surf 4.2m',
 5.0, 30.0, 'Rochoso abrupto', false, true, 4, 89),

('Portinho da Arrábida',
 38.4876, -8.9816, 'PT', 'Setúbal', 'costa', 'pro',
 ARRAY['Robalo','Sargo','Dourada'],
 ARRAY['Primavera','Verão','Outono'],
 ARRAY['Lula','Borracha shad'],
 'Bóia / Spinning', 'Spinning 9–11ft',
 3.0, 20.0, 'Rochoso / posidónia', true, true, 2, 86),

('Costa da Caparica — Pontão',
 38.5357, -9.2351, 'PT', 'Lisboa', 'costa', 'free',
 ARRAY['Robalo','Linguado'],
 ARRAY['Outono','Inverno'],
 ARRAY['Minhoca','Amêijoa'],
 'Surfcasting', 'Surf 4.2m',
 1.0, 5.0, 'Areia', true, true, 1, 73),

('Porto Covo',
 37.8473, -8.7856, 'PT', 'Alentejo Litoral', 'costa', 'free',
 ARRAY['Robalo','Sargo','Corvina'],
 ARRAY['Outono','Inverno'],
 ARRAY['Borracha shad','Lula'],
 'Spinning', 'Spinning 9–11ft',
 3.0, 25.0, 'Rochoso', true, true, 3, 82),

('Vila Nova de Milfontes',
 37.7238, -8.7884, 'PT', 'Alentejo Litoral', 'costa', 'free',
 ARRAY['Robalo','Sargo'],
 ARRAY['Outono','Inverno'],
 ARRAY['Borracha shad','Lula'],
 'Spinning', 'Spinning 9–11ft',
 2.0, 15.0, 'Areia e rocha', true, true, 2, 78),

('Sines — Praia Vasco da Gama',
 37.9601, -8.8744, 'PT', 'Alentejo Litoral', 'costa', 'free',
 ARRAY['Robalo','Sargo'],
 ARRAY['Outono','Inverno'],
 ARRAY['Borracha shad','Minhoca'],
 'Surfcasting', 'Surf 4.0m',
 1.0, 8.0, 'Areia e rocha', true, true, 2, 75),

('Ilha da Culatra — Olhão',
 36.9980, -7.8774, 'PT', 'Algarve', 'costa', 'pro',
 ARRAY['Dourada','Linguado','Robalo'],
 ARRAY['Primavera','Verão'],
 ARRAY['Amêijoa','Camarão'],
 'Bóia', 'Float 3–4m',
 1.0, 5.0, 'Areia vasosa', false, false, 2, 87),

('Ria Formosa — Tavira',
 37.1100, -7.6500, 'PT', 'Algarve', 'costa', 'free',
 ARRAY['Dourada','Linguado','Robalo'],
 ARRAY['Primavera','Verão','Outono'],
 ARRAY['Amêijoa','Camarão'],
 'Fundo', 'Float 3–4m',
 1.0, 4.0, 'Areia vasosa', true, true, 1, 80),

('Vila Real de Santo António — Molhe',
 37.1928, -7.4112, 'PT', 'Algarve', 'costa', 'free',
 ARRAY['Robalo','Dourada','Linguado'],
 ARRAY['Outono','Inverno'],
 ARRAY['Lula','Minhoca'],
 'Fundo', 'Float 3–4m',
 2.0, 6.0, 'Areia', true, true, 1, 78),

('Ericeira',
 38.9612, -9.4170, 'PT', 'Oeste', 'costa', 'free',
 ARRAY['Robalo','Sargo'],
 ARRAY['Outono','Inverno'],
 ARRAY['Borracha shad','Lula'],
 'Spinning', 'Spinning 9–11ft',
 2.0, 15.0, 'Rochoso', true, true, 2, 80),

('Praia de Mira',
 40.4297, -8.7912, 'PT', 'Centro', 'costa', 'free',
 ARRAY['Linguado','Robalo'],
 ARRAY['Verão','Outono'],
 ARRAY['Minhoca','Amêijoa'],
 'Surfcasting', 'Surf 4.2m',
 1.0, 4.0, 'Areia', true, true, 1, 71),

-- ── PORTUGAL RIO / BARRAGEM ───────────────────────────────────────────────────

('Rio Tejo — Constância',
 39.4752, -8.3310, 'PT', 'Ribatejo', 'rio', 'free',
 ARRAY['Barbo','Achigã','Enguia'],
 ARRAY['Primavera','Outono'],
 ARRAY['Milho','Minhoca','Pellet'],
 'Fundo', 'Bottom 3.6–4m',
 2.0, 8.0, 'Areia e seixo', true, true, 1, 76),

('Rio Tejo — Abrantes',
 39.4637, -8.1980, 'PT', 'Ribatejo', 'rio', 'free',
 ARRAY['Barbo','Carpa'],
 ARRAY['Primavera','Verão'],
 ARRAY['Milho','Pellet'],
 'Feeder', 'Feeder 3.6m',
 2.0, 6.0, 'Areia e lama', true, true, 1, 73),

('Barragem de Alqueva',
 38.1993, -7.4978, 'PT', 'Alentejo', 'barragem', 'free',
 ARRAY['Achigã','Carpa','Lúcio-perca'],
 ARRAY['Primavera','Verão','Outono'],
 ARRAY['Shad 12cm','Minhoca'],
 'Spinning', 'Bait 6–8ft',
 5.0, 50.0, 'Lama e vegetação', true, true, 2, 85),

('Barragem de Castelo de Bode',
 39.5373, -8.2882, 'PT', 'Ribatejo', 'barragem', 'pro',
 ARRAY['Achigã','Truta'],
 ARRAY['Primavera','Outono'],
 ARRAY['Shad 10cm','Jig'],
 'Spinning', 'Bait 6–8ft',
 10.0, 80.0, 'Rochoso', true, true, 2, 86),

('Rio Douro — Pocinho',
 41.1271, -7.0892, 'PT', 'Norte', 'rio', 'pro',
 ARRAY['Barbo','Truta'],
 ARRAY['Primavera','Outono'],
 ARRAY['Minhoca','Mosca seca'],
 'Fly', 'Fly 9ft',
 1.0, 10.0, 'Seixo e rocha', true, false, 3, 82),

('Rio Minho — Valença',
 42.0267, -8.6404, 'PT', 'Minho', 'rio', 'pro',
 ARRAY['Sável','Robalo','Barbo'],
 ARRAY['Primavera','Verão'],
 ARRAY['Mosca molhada','Calamar'],
 'Float', 'Float 3–4m',
 2.0, 12.0, 'Seixo e areia', true, true, 2, 80),

('Rio Sado — Alcácer do Sal',
 38.3611, -8.5151, 'PT', 'Alentejo', 'rio', 'free',
 ARRAY['Robalo','Dourada','Achigã'],
 ARRAY['Primavera','Outono'],
 ARRAY['Lula','Shad 10cm'],
 'Spinning', 'Spinning 9–11ft',
 1.0, 6.0, 'Areia e lama', true, true, 1, 78),

('Rio Guadiana — Mértola',
 37.6384, -7.6614, 'PT', 'Alentejo', 'rio', 'free',
 ARRAY['Barbo','Lúcio','Achigã'],
 ARRAY['Primavera','Outono'],
 ARRAY['Minhoca','Shad 10cm'],
 'Fundo', 'Bottom 3.6m',
 2.0, 15.0, 'Rocha e areia', true, true, 2, 77),

('Rio Lima — Ponte de Lima',
 41.7702, -8.5839, 'PT', 'Minho', 'rio', 'free',
 ARRAY['Truta','Sável','Barbo'],
 ARRAY['Primavera','Verão'],
 ARRAY['Mosca seca','Milho'],
 'Fly', 'Fly 9ft',
 1.0, 4.0, 'Seixo e areia', true, true, 2, 74),

('Rio Mondego — Coimbra',
 40.2054, -8.4291, 'PT', 'Centro', 'rio', 'free',
 ARRAY['Barbo','Achigã','Enguia'],
 ARRAY['Primavera','Outono'],
 ARRAY['Milho','Minhoca'],
 'Fundo', 'Bottom 3.6m',
 1.0, 5.0, 'Areia e seixo', true, true, 1, 72),

-- ── ESPANHA COSTA ─────────────────────────────────────────────────────────────

('Ría de Vigo',
 42.2336, -8.7231, 'ES', 'Galicia', 'costa', 'free',
 ARRAY['Robalo','Dourada','Sargo'],
 ARRAY['Primavera','Outono'],
 ARRAY['Borracha shad','Amêijoa'],
 'Spinning', 'Spinning 9–11ft',
 2.0, 15.0, 'Fundos mistos', true, true, 2, 80),

('A Guarda — Costa',
 41.9012, -8.8743, 'ES', 'Galicia', 'costa', 'free',
 ARRAY['Robalo','Sargo'],
 ARRAY['Outono','Inverno'],
 ARRAY['Lula','Borracha shad'],
 'Surfcasting', 'Surf 4.0m',
 2.0, 12.0, 'Rochoso', true, true, 2, 78),

('Punta Umbría — Huelva',
 37.1875, -6.9610, 'ES', 'Andalucia', 'costa', 'free',
 ARRAY['Robalo','Dourada','Linguado'],
 ARRAY['Outono','Inverno'],
 ARRAY['Minhoca','Camarão'],
 'Surfcasting', 'Surf 4.2m',
 1.0, 5.0, 'Areia', true, true, 1, 76),

('Cádiz — La Caleta',
 36.5269, -6.3076, 'ES', 'Andalucia', 'costa', 'free',
 ARRAY['Dourada','Sargo'],
 ARRAY['Primavera','Outono'],
 ARRAY['Amêijoa','Camarão'],
 'Surfcasting', 'Surf 4.0m',
 1.0, 8.0, 'Areia', true, true, 1, 77),

('Tarifa',
 36.0141, -5.6018, 'ES', 'Andalucia', 'costa', 'pro',
 ARRAY['Robalo','Sargo','Atum'],
 ARRAY['Verão','Outono'],
 ARRAY['Lula','Borracha shad'],
 'Spinning', 'Spinning 9–11ft',
 3.0, 20.0, 'Rochoso', true, true, 3, 82),

('Llanes — Asturias',
 43.4196, -4.7545, 'ES', 'Asturias', 'costa', 'free',
 ARRAY['Sargo','Robalo','Pargo'],
 ARRAY['Primavera','Outono'],
 ARRAY['Borracha shad','Sarda'],
 'Spinning', 'Spinning 9–11ft',
 2.0, 18.0, 'Rochoso', true, true, 3, 79),

('San Vicente de la Barquera',
 43.3818, -4.3941, 'ES', 'Cantabria', 'costa', 'free',
 ARRAY['Robalo','Sargo'],
 ARRAY['Primavera','Outono'],
 ARRAY['Borracha shad','Lula'],
 'Surfcasting', 'Surf 4.0m',
 2.0, 10.0, 'Areia e rocha', true, true, 2, 78),

('Mundaka — Bizkaia',
 43.4064, -2.6953, 'ES', 'País Vasco', 'costa', 'pro',
 ARRAY['Robalo','Dourada'],
 ARRAY['Primavera','Outono'],
 ARRAY['Borracha shad','Lula'],
 'Spinning', 'Spinning 9–11ft',
 2.0, 12.0, 'Areia e rochoso', true, true, 2, 82),

('Hondarribia',
 43.3683, -1.7955, 'ES', 'País Vasco', 'costa', 'free',
 ARRAY['Robalo','Dourada'],
 ARRAY['Primavera','Outono'],
 ARRAY['Borracha shad','Amêijoa'],
 'Spinning', 'Spinning 9–11ft',
 1.0, 8.0, 'Areia e rocha', true, true, 2, 77),

('Baiona — Pontevedra',
 42.1191, -8.8406, 'ES', 'Galicia', 'costa', 'free',
 ARRAY['Robalo','Sargo'],
 ARRAY['Primavera','Outono'],
 ARRAY['Borracha shad','Lula'],
 'Spinning', 'Spinning 9–11ft',
 2.0, 12.0, 'Rochoso', true, true, 2, 78),

-- ── ESPANHA RIO / BARRAGEM ────────────────────────────────────────────────────

('Rio Tajo — Aranjuez',
 40.0322, -3.6077, 'ES', 'Castilla-La Mancha', 'rio', 'free',
 ARRAY['Barbo','Achigã'],
 ARRAY['Primavera','Outono'],
 ARRAY['Milho','Minhoca'],
 'Fundo', 'Bottom 3.6m',
 2.0, 6.0, 'Areia e seixo', true, true, 1, 73),

('Embalse de Mequinenza — Ebro',
 41.3704, 0.2918, 'ES', 'Aragón', 'barragem', 'pro',
 ARRAY['Carpa','Siluro','Barbo'],
 ARRAY['Primavera','Outono'],
 ARRAY['Pellet','Milho','Boilies'],
 'Feeder', 'Feeder 3.6–4.2m',
 5.0, 40.0, 'Areia e pedra', true, true, 2, 84),

('Embalse de Orellana — Badajoz',
 38.9988, -5.4613, 'ES', 'Extremadura', 'barragem', 'free',
 ARRAY['Carpa','Barbo','Tenca'],
 ARRAY['Primavera','Outono'],
 ARRAY['Pellet','Milho','Gusanos'],
 'Feeder', 'Feeder 3.6m',
 3.0, 20.0, 'Areia e lama', true, true, 1, 79),

('Rio Sil — Galicia',
 42.4093, -7.2117, 'ES', 'Galicia', 'rio', 'pro',
 ARRAY['Truta','Salmão'],
 ARRAY['Primavera','Verão'],
 ARRAY['Mosca seca','Ninfa'],
 'Fly', 'Fly 9ft',
 1.0, 5.0, 'Seixo e rocha', false, true, 4, 83),

('Rio Miño — Tui',
 42.0461, -8.6490, 'ES', 'Galicia', 'rio', 'pro',
 ARRAY['Sável','Salmão','Barbo'],
 ARRAY['Primavera','Verão'],
 ARRAY['Mosca molhada','Calamar'],
 'Float', 'Float 3–4m',
 2.0, 10.0, 'Seixo e areia', true, true, 2, 82),

('Embalse de Bornos — Cádiz',
 36.8079, -5.7183, 'ES', 'Andalucia', 'barragem', 'free',
 ARRAY['Carpa','Barbo'],
 ARRAY['Primavera','Outono'],
 ARRAY['Pellet','Milho'],
 'Feeder', 'Feeder 3.6m',
 2.0, 15.0, 'Areia e lama', true, true, 1, 76);
